services:
  - type: web
    name: zerkalo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
